// Generated by tools/seed_c.py for the execution loop.
// Edit freely; this is a seed, not the final answer.

#include <ultra64.h>
// DLIST_HINT: if this function builds/walks Gfx*, add `#include <PR/gbi.h>`
//             and run gfxdis on any static dlists in target.rodata.s.

// SEED WARNING: rodata labels not found in asm/data/:
//   - D_80099999

// === Externs from parent file ===
extern u32 gFoo;
extern void siblingFn(void); // TODO: refine signature from MCP
// --- auto-extern (refine types during iteration) ---
extern void *D_80022222;

/* === m2c reference (do not compile) =========================== */
#if 0
int m2c_ref(void) { return 0; }
#endif
/* === end m2c reference ========================================= */

// === Function body ============================================
u32 func_80012345(void)
{
    return 0;
}
