.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

/* Handwritten function */
nonmatching _start, 0x3C

glabel _start
    /* 1000 80025C00 3C08800D */  lui        $t0, %hi(main_BSS_START)
    /* 1004 80025C04 25082930 */  addiu      $t0, $t0, %lo(main_BSS_START)
    /* 1008 80025C08 3C090012 */  lui        $t1, %hi(main_BSS_SIZE)
    /* 100C 80025C0C 25292100 */  addiu      $t1, $t1, %lo(main_BSS_SIZE)
  .L80025C10:
    /* 1010 80025C10 AD000000 */  sw         $zero, 0x0($t0)
    /* 1014 80025C14 AD000004 */  sw         $zero, 0x4($t0)
    /* 1018 80025C18 21080008 */  addi       $t0, $t0, 0x8 /* handwritten instruction */
    /* 101C 80025C1C 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1020 80025C20 1520FFFB */  bnez       $t1, .L80025C10
    /* 1024 80025C24 00000000 */   nop
    /* 1028 80025C28 3C0A800A */  lui        $t2, %hi(main)
    /* 102C 80025C2C 254A94B0 */  addiu      $t2, $t2, %lo(main)
    /* 1030 80025C30 3C1D8011 */  lui        $sp, %hi(D_8010C2D0)
    /* 1034 80025C34 01400008 */  jr         $t2
    /* 1038 80025C38 27BDC2D0 */   addiu     $sp, $sp, %lo(D_8010C2D0)
endlabel _start
    /* 103C 80025C3C 00000000 */  nop
    /* 1040 80025C40 00000000 */  nop
    /* 1044 80025C44 00000000 */  nop
    /* 1048 80025C48 00000000 */  nop
    /* 104C 80025C4C 00000000 */  nop
